# 第 1 章 向量和向量空间

## 1.1 向量

### 1.1.1 描述向量

《跟老齐学 Python：数据分析》

《Python 大学实用教程》

《数据准备和特征工程》

In [1]:
import numpy as np
u = np.array([1, 6, 7])
u

array([1, 6, 7])

In [2]:
v = u.reshape(-1, 1)
v

array([[1],
       [6],
       [7]])

In [3]:
import random, time

# 创建一个列表
lst = [random.randint(1, 100) for i in range(100000)]


start = time.time()
lst2 = [i*i for i in lst]    # 用列表解析的方式计算每个数的平方
end = time.time()
print(f"列表解析用时： {end - start}s")

vlst = np.array(lst)    # 将列表转换为数组表示的向量
start2 = time.time()
vlst2 = vlst * vlst    # 用数组相乘计算每个数的平方
end2 = time.time()
print(f"数组（向量）运算用时：{end2 - start2}s")
print(f"列表解析的运算时间是向量运算时间的：{round((end-start)/(end2-start2), 3)}倍")

列表解析用时： 0.008679866790771484s
数组（向量）运算用时：0.0005750656127929688s
列表解析的运算时间是向量运算时间的：15.094倍


**应用：NLP**

d1: mathematics machine learn

d2: learn python learn mathematics

![](./lessonimages/ml.png)

$\pmb{d}_1 = \begin{bmatrix}1&1&1&0\end{bmatrix}$，$\pmb{d}_2 = \begin{bmatrix}2&0&1&1\end{bmatrix}$

**词袋**

In [5]:
from sklearn.feature_extraction.text import CountVectorizer  
vectorizer=CountVectorizer()                                              # (1)
corpus=["mathematics machine learn", "learn python learn mathematics"]    # (2)
cor_vec = vectorizer.fit_transform(corpus)                                # (3)
vectorizer.get_feature_names()                                            # (4)

['learn', 'machine', 'mathematics', 'python']

In [6]:
print(cor_vec)

  (0, 2)	1
  (0, 1)	1
  (0, 0)	1
  (1, 2)	1
  (1, 0)	2
  (1, 3)	1


In [7]:
import pandas as pd
df = pd.DataFrame(cor_vec.toarray(), columns=vectorizer.get_feature_names())
df

learn  machine  mathematics  python
0      1        1            1       0
1      2        0            1       1

**字词频数** $n_{ij}$

**字词频率** tf

**逆向文件频率** idf

tf-idf

In [8]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_trans = TfidfTransformer()
tfidf = tfidf_trans.fit_transform(cor_vec)

# 每个字词的idf
tfidf_trans.idf_

array([1.        , 1.40546511, 1.        , 1.40546511])

In [9]:
tfidf.toarray()

array([[0.50154891, 0.70490949, 0.50154891, 0.        ],
       [0.75726441, 0.        , 0.37863221, 0.53215436]])

### 1.1.2 向量的加法

In [10]:
import numpy as np
np.array([[2],[1]]) + np.array([[3], [3]])

array([[5],
       [4]])

In [11]:
np.array([[2],[1]]) - np.array([[3], [3]])

array([[-1],
       [-2]])

**1.1.3 向量的数量乘法**

In [12]:
2 * np.array([[3], [1]])

array([[6],
       [2]])

In [13]:
-1 * np.array([[3], [1]])

array([[-3],
       [-1]])